# Generated by Django 5.1.7 on 2025-03-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_alter_market_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='market',
            new_name='markets',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='sellers',
        ),
    ]
