# Generated by Django 5.1.7 on 2025-03-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0004_rename_market_product_markets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='markets',
            new_name='market',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sellers',
            new_name='seller',
        ),
    ]
